{
  "mcpServers": {
    "Context7": {
      "command": "C:\\Program Files\\nodejs\\npx.cmd",
      "args": [
        "-y",
        "@upstash/context7-mcp@latest",
        "--api-key",
        "ctx7sk-9ceeeef9-1751-46e9-9187-2e0bbfcd97ad",
        "--transport",
        "stdio"
      ],
      "env": {},
      "disabled": false,
      "autoApprove": []
    }
  }
}
